### ISSUE TITLE
Escolher 5 sites para analisar

### ISSUE THREAD

**Issue by G16C** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#1]
## Descrição
Essa issue tem como objetivo a procura e seleção dos 5 sites a serem avaliados, com a finalidade de escolhermos 1 como objeto de estudo na disciplina

## Tarefas
- [x] Encontrar 5 sites para analise inicial

## Critério de aceitação
- [x] Os sites devem ter um bom número de usuários. Também há de se levar em consideração a comunicação com estes usuários, tendo em vista facilitar o desenvolvimento do trabalho

**Comment by mathonaut** [comment]
Dividi as recomendações em dois grupos: críticos (sites que possuem muitos elementos para ser analisados ou criados/ajustados) e não críticos (aqueles onde os problemas são menores ou com elementos de ajuste mais fáceis). Segue lista:

Críticos:
+ Central Expresso - https://www.centralexpresso.com/index.html
+ Agência Espacial Brasileira - https://www.gov.br/aeb/pt-br

Não Críticos:
+ Memorial JK - http://www.memorialjk.com.br/pt/
+ Cine Drive-In - https://cinedrivein.com/
+ Capital Moto Week - https://www.capitalmotoweek.com.br/

**Comment by manuziny** [comment]
Escolhi sites de iniciativa privada e pública. O critério usado foi mais pelos usuários de cada um, são usuários que seriam mais fáceis de serem encontrados na FGA e/ou até mesmo no nosso nicho. Assim poderíamos fazer nossas pesquisas sem muitas dificuldades em achar o público de cada site.

Pública:

- Nesp - https://www.nesp.unb.br/
- Cebraspe - https://www.cebraspe.org.br/
- JusBrasil - https://www.jusbrasil.com.br/

Privada:

- Casado Calçado - https://www.casadocalcados.com.br/
- LJL Uniformes - https://ljluniformesbsb.com.br/

**Comment by G16C** [comment]
Decidi selecionar sites de uso recorrente na minha família visando maior proximidade com minha realidade, assim como com os usuários. Em alguns dos sites escolhidos há uma clara desatualização da interface o que pode proporcionar mais dados para o projeto.

Pública: 

- Câmara dos Deputados: https://www.camara.leg.br/
- Detran: https://www.detran.df.gov.br
- Instituto Federal de Brasília: https://www.ifb.edu.br

Privada:

- Netshoes: https://www.netshoes.com.br
- Casas Bahia: https://www.casasbahia.com.br

**Comment by RafaelCLG0** [comment]
Os sites escolhidos foram baseados em um perfil de usuário comum e com bom número de usuários que o utilizem são eles:

Públicos:

* Exército Brasileiro: https://www.eb.mil.br
* DF no Ponto: https://dfnoponto.semob.df.gov.br

Privados:

* Mercado Livre: https://www.mercadolivre.com.br
*  OLX: https://www.olx.com.br
*  MeuID: https://idwall.co/meuid-empresas/

**Comment by manuziny** [comment]
O site escolhido não está listado, pois foi escolhido após discussão em sala de aula, que foi a escolha do Bilheteria Digital
