### ISSUE TITLE
Documentação para Entrega Final.

### ISSUE THREAD

**Issue by RafaelCLG0** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#100]
## Descrição
Realizar a Entrega Final de acordo com os parâmetros passados pelo professor.

## Tarefas
A apresentação do projeto final da disciplina de Requisitos de Software deve possuir os seguintes tópicos:
- [x] 1. O site selecionado para o projeto (justificativa: o motivo da escolha e os aspectos selecionados para trabalhar no projeto);
- [x] 2. O ciclo de vida utilizado no projeto (justificativa: o motivo da escolha);
- [x] 3. O planejamento dos recursos e das entregas (cronograma planejado e executado);
- [x] 4. A execução do projeto (de cada etapa do ciclo de vida);
- [x] 5. O(s) resultado(s) alcançado(s) com a execução do projeto (em relação ao objetivo do projeto).
- [x] 6. Uma tabela sintetizando quais ferramentas e onde elas foram utilizadas em cada etapa do projeto.
- [x] 7. Uma tabela sintetizando quais técnicas foram utilizadas na execução do projeto com o(s) nome(s) do(s)
participantes(s) do grupo que usou/usaram cada uma das técnicas;
- [ ] 8. Uma tabela sintetizando quais artefatos foram criados no projeto em cada etapa do projeto com autor
e revisor;
- [x] 9. Uma tabela sintetizando as avaliações dos protótipos com entrevistadores e o número de participantes com
os nomes do participantes do grupo que participaram da avaliação ;
- [x]  10. Uma tabela sintetizando o método de verificação dos artefatos com autor e revisor (do checklist e da
verificação);
- [x]  11. Uma tabela sintetizando quais ferramentas e onde elas foram utilizadas em cada etapa do projeto.
- [x]  12. Uma tabela sintetizando os vídeos das apresentações de cada etapa com o(s) nome(s) do(s) participantes(s)
do grupo que participaram das gravações).

## Critério de aceitação
- [x] Seguir todas essa etapas para a Entrega Final Projeto final da disciplina

**Comment by manuziny** [comment]
itens 5 e 9 já nas branch de entrega final e muito sujeito a correções.

**Comment by mathonaut** [comment]
Itens 6, 8 e 11 documentados.

**Comment by manuziny** [comment]
Todos os tópicos estão presentes da página da entrega final.
