### ISSUE TITLE
Analisar projetos anteriores

### ISSUE THREAD

**Issue by arthurgrandao** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#2]
## Descrição
Procurar e analisar projetos anteriores para auxiliar nosso projeto.

## Tarefas

- [x] Procurar e analisar os projetos anteriores;
- [x] Listar as técnicas, tecnologias e metodologias utilizadas;

## Critério de aceitação

- [x] Apresentar ao grupo o resultado da pesquisa;

**Comment by mathonaut** [comment]
A análise se deu nos 64 projetos presente no repositório da disciplina. Foram utilizadas ao todo 38 ferramentas.

  Em relação às tecnologias utilizadas, elas focam na produtividade da equipe como ferramentas para desenho de diagramas, organização de equipes e criação de protótipos digitalizados.

  Outrossim, as metodologias e técnicas, são uma mistura de técnicas de desenvolvimento ágil com os frameworks de análise de análise de interação humano computador como o DECIDE e o ciclo de vida da Mayhew.

  Abaixo segue a lista com os os sites já utilizados:

- AliExpress
- Aprender3
- BCE - Biblioteca Central da UnB
- Berkshire Hathaway
- Blog do Sigi Vilares
- Brasil Channel
- BRB Mobilidade
- CD-MOJ
- Cebraspe
- Centro de Integração Empresa-Escola (CIEE)
- Cil2bsb
- CodeForces
- Conect.ideias
- Corpo de Bombeiros Militar Do Distrito Federal - CBMDF
- CPlusPlus
- Defensoria Pública do Estado de São Paulo
- Detran-DF
- Estagiarios.com
- Exército Brasileiro
- Faculdade de Arquitetura e Urbanismo
- FENACELBRA
- FindGlocal
- forumPiR2
- Ingresso.EEAR(Escola de Especialistas da Aeronáutica)
- Lancenet
- Lichess
- Millenium Papelaria e Presentes
- MPU
- MusikCity
- Neoenergia
- Nota Legal
- Polícia Civil do Distrito Federal
- Polícia Militar do Distrito Federal (PMDF)
- Polícia Militar do estado da Bahia
- Prefeitura de Águas Lindas de Goiás
- Prefeitura de Concórdia
- Prefeitura de João Pessoa
- Prefeitura de Londrina
- Prefeitura de Passo Fundo
- Prefeitura de Patos de Minas
- Prefeitura de Sorocaba
- Prefeitura Municipal de Arco-íris
- Prefeitura Municipal de Itabuna
- Prefeitura Municipal de São Sebastião do Alto
- Prefeitura de Araguaina
- Prefeitura Unai
- Prefeitura Verdelândia
- SamuelPereiraei(imobiliaria)
- Secretaria de Educação do DF
- Secretária de Transporte e Mobilidade do DF
- SIGAA-UNB
- Simples Nacional
- Sistema de Apoio Educacional(SAE)
- Sistema Eletrônico de Informações (SEI)(TRF4)
- Site Domínio Público
- Skoob
- Terra
- Tribunal de Justiça do Estado do Amapá
- UnB Idiomas
- UVa online judge
- Vjudge
- Wish
- YALE
- ZUPPER

A lista a seguir mostra as tecnologias utilizadas:

- Adobe   Photoshop
- Canva
- Clipchamp
- CodeForces
- Coolors
- Discord
- Draw.io
- Excel
- Figma
- Firefox
- Git
- Github
- Google   Chrome
- Google   Docs
- Google   Drive
- Google   Forms
- Google   Meets
- Google   Planilhas
- Google   Scholar
- Kdenlive   (KDE Non-Linear Video Editor)
- Lucidchart
- Microsoft   PowerPoint
- Microsoft   Teams
- Miro
- MkDocs
- OBStudio
- Office
- Storyboard   That
- Telegram
- This   Person Doesn't Exist
- UXPRESSIA
- Visual   Studio
- WhatsApp
- Youtube
- Intellij
- Vegas   Pro
- Google   Workspace
- Zenhub
