### ISSUE TITLE
Criação do Perfil de Usuário

### ISSUE THREAD

**Issue by RafaelCLG0** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#22]
## Descrição
Elaborar o Perfil de Usuário do site Bilheteria Digital.

## Tarefas
- [x] Elaborar um grupo de foco para traçar um Perfil de Usuário.
- [x] Analisar as respostas dos participantes e documentar o resultado.
- [x] Criar a documentação do Perfil de Usuário.
- [x] Criar o Perfil de Usuário de acordo com os critérios passado pelo professor.

## Critério de aceitação
- [x] Documentação do grupo de foco realizado.
- [x] Documentação criada sobre o Perfil de Usuário.
- [x] Perfil de Usuário de acordo com os critérios passado pelo professor.

**Comment by manuziny** [comment]
todos os critérios já foram atendidos e está registrado na git page.
