### ISSUE TITLE
Análise de Tarefas

### ISSUE THREAD

**Issue by arthurmlv** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#27]
## Descrição
Realização da análise de tarefas e documentação de tal na aba de análise de requisitos.

## Tarefas
- [x] Realizar a análise de tarefas;
- [ ] Documentá-la na página criada.

## Critério de aceitação
- [x] Documentação realizada e revisada da análise de tarefas na aba especificada.

**Comment by manuziny** [comment]
Todos os critérios já foram feitos e já está tudo na git page.
