### ISSUE TITLE
Metas de usabilidade

### ISSUE THREAD

**Issue by manuziny** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#38]
## Descrição
Realizar e documentar as metas de usabilidade do projeto.
## Tarefas

- [x] Documentar as metas de usabilidade
- [x] Implementar da gitpage

## Critério de aceitação

- [x]  Possuir as metas de usabilidade que devem ser alcançadas no projeto
- [x]  Possuir a razão da seleção das metas de usabilidade
- [x]  Estar na gitpage

**Comment by mathonaut** [comment]
Artefato concluído.
