### ISSUE TITLE
Criação do cronograma

### ISSUE THREAD

**Issue by arthurmlv** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#5]
## Descrição
Criar o cronograma de acordo com as demandas do professor e implementá-lo em markdown.

## Tarefas
- [x] Criar o cronograma planejado e o executado
- [x] Implementá-lo na Git Page

## Critério de aceitação
- [x] Ambos os cronogramas criados
- [x] Ambos visíveis na Git Page, separados por entrega e citados no texto

**Comment by manuziny** [comment]
O cronograma já está na página da disciplina e atualizado com as modificações solicitadas na reunião.
