### ISSUE TITLE
Relato do Resultado - Análise de Tarefas

### ISSUE THREAD

**Issue by G16C** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#57]
## Descrição
Documentar o relato do resultado da avaliação da Análise de Tarefas
## Tarefas

- [x] Adicionar os vídeos com as gravações das reuniões realizadas durante a avaliação do Análise de Tarefas
- [x] Adicionar tabelas com participantes (entrevistados e entrevistadores) e as respostas obtidas

## Critério de aceitação
- [x] O documento deve estar em uma branch (relato-do-resultado-avaliação)
- [x] Deve cumprir com os padrões definidos no planejamento e na checklist do professor

**Comment by manuziny** [comment]
Adição de todos os vídeos das entrevistas e teste piloto.
