### ISSUE TITLE
Ajustes etapa 5

### ISSUE THREAD

**Issue by manuziny** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#73]
## Descrição
Ajustar de acordo com as recomendações do professor a etapa 5.

## Tarefas

- [x] Realizar os ajustes.

## Critério de aceitação

- [x] Estar na gitpage;
- [x] Adicionar no histórico de versões.

**Comment by RafaelCLG0** [comment]
✔️ Ajustes etapa 5
