### ISSUE TITLE
Documentar metodologias

### ISSUE THREAD

**Issue by dougAlvs** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#8]
## Descrição

É preciso que as metodologias usadas no projeto sejam documentadas e adicionadas na gitpage do repositório.

## Tarefas

- Adicionar documentação das metodologias na gitpage

## Critério de aceitação

- [x] Página de metodologias adicionada na gitpage

**Comment by arthurmlv** [comment]
Metodologia adicionada na gitpage.
