### ISSUE TITLE
Relato do protótipo de alta fidelidade

### ISSUE THREAD

**Issue by manuziny** [Interacao-Humano-Computador/2023.1-BilheteriaDigital#95]
## Descrição
Elaborar a documentação do relato do protótipo de alta fidelidade.

## Tarefas

- [x] Colocar as entrevistas 
- [x] Documentar os relatos

## Critério de aceitação

- [x] Estar na gitpage.

**Comment by mathonaut** [comment]
Issue concluída e documentada na página do grupo.
